---
- name: Apply role ceph-mon
  hosts: "{{ mon_group_name|default('ceph-mon') }}"
  become: true
  serial: '{{ ceph_serial|default("0") }}'
  strategy: "{{ osism_strategy|default('linear') }}"

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-mon
