---
- name: Apply role ceph-nfs
  hosts: "{{ nfs_group_name|default('ceph-nfs') }}"
  become: true
  serial: '{{ ceph_serial|default("0") }}'

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-nfs
