---
- name: Apply role ceph-infra
  hosts: "{{ ceph_group_name|default('ceph') }}"
  become: true
  serial: '{{ ceph_serial|default("0") }}'
  strategy: "{{ osism_strategy|default('linear') }}"

  roles:
    - ceph-infra
