---
- name: Apply role ceph-rbd-mirror
  hosts: "{{ rbdmirror_group_name|default('ceph-rbdmirror') }}"
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-rbd-mirror
