---
- name: Run ceph-mons play
  ansible.builtin.import_playbook: ceph-mons.yml

- name: Run ceph-mgrs play
  ansible.builtin.import_playbook: ceph-mgrs.yml

- name: Run ceph-osds play
  ansible.builtin.import_playbook: ceph-osds.yml

- name: Run ceph-crash play
  ansible.builtin.import_playbook: ceph-crash.yml
  when: enable_ceph_crash|default(true)|bool

- name: Run ceph-mdss play
  ansible.builtin.import_playbook: ceph-mdss.yml
  when: enable_ceph_mds|default(false)|bool

- name: Run ceph-rgws play
  ansible.builtin.import_playbook: ceph-rgws.yml
  when: enable_ceph_rgw|default(false)|bool
