---
- name: Apply role ceph-restapi
  hosts: "{{ restapi_group_name|default('ceph-restapi') }}"
  become: true
  serial: '{{ ceph_serial|default("0") }}'

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-restapi
