---
- name: Apply role ceph-restapi
  gather_facts: false
  hosts: ceph-restapi
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-restapi
