---
dist: bionic
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/ceph-ansible
  matrix:
    - CEPH_VERSION=master UBUNTU_VERSION=20.04
    - CEPH_VERSION=luminous UBUNTU_VERSION=18.04
    - CEPH_VERSION=nautilus UBUNTU_VERSION=20.04
    - CEPH_VERSION=octopus UBUNTU_VERSION=20.04

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh
  - bash scripts/test.sh

deploy:
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: tags

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
