---
extends: default

rules:
  comments: enable
  line-length: disable

# ignore playbooks imported from upstream
ignore: |
  files/playbooks/*/ceph-purge-cluster.yml
  files/playbooks/*/ceph-purge-storage-node.yml
