---
extends: default

rules:
  comments: enable
  indentation: disable
  line-length: disable

# ignore playbooks imported from upstream
ignore: |
  files/playbooks/pacific/ceph-purge-cluster.yml
  files/playbooks/quincy/ceph-purge-cluster.yml
