---
- secret:
    name: SECRET_CONTAINER_IMAGE_CEPH_ANSIBLE
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - EDeEMGO2BPbzFiljCqhot/wZZEmh8P64wxqccTfk1n6rKS9IM8dhe3wZjo2SKnzhLJiHv
          fGaWFF5fFt/9AegspZhkzP1oMMsLXd400JhKUFAL3V8KVBNN/qAOd1Cavzaa3BjXxFqcW
          AJTTllUtzVMzHiqp278Cd0hhLPQircQi8hspCRdRpljfYDHh90jDZDAlxL3/mfmjUEHNU
          gFUZEBv4wpkwI2rmaeURO/U8hyQ/0seStcrOdwPRU5jxLvNpbHrlQ5bsuQeCxpODEHyQO
          6rlEM3do82Ujd5Ios4kJ/pGr76yrVqNJq+d/OB5OxuTeHTBJvWNK6VVk3I7rzjP8t+w8+
          uQkrgBpdxVKS6Ib1YgIwCTperc482LX9+U+56TYFxtq4NiMP+xaraqocUsg6pZh6B7ev8
          wlfHpp0DoyxmW5hCzKl+oJAdtRYqOGN9uRm65VDCnN4DvVpaWsmejrPp17qK+zj//Ckn/
          q/xnBJS2ZZvQYB9NuSbMNySt4C1N+mVtCFqAhY6EX931JtfuNlWX59U/eclH/0qXt5eyI
          kw355ExitQD6wu0JAa0civfa2mx4aHxX5OpWcUAxDPngm956Ut4LYteqTzeEsk+TJRDM9
          /ZR1LvNVaTZEw//fWElULmQl//AfekY8Z/9YV8+vYxpKCnWvFmaS40Z8XOjqqc=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - XRrO3OAbGoS67lvQXK0vHDJizupVCR8516cGi16tj9wd6OdieK7hHTEV1RXOs4RS/jJNi
          nClPuKYokT1vob8n7RyXZ5MCoEivsblaTMFZ7t3TOne+KB9GvutfbLNuqv7cesUatw8lR
          0NTmypajiUgftI3XOoUA4t0RetKDCifPnif7D0WDfGRxAk0EH7lSxtZwGXIuLu9Mtxyda
          EeKSVxGdnjrJA5K4Q3tXuPHzgvLJbEfL50ZXJJKtd5gnOh1uJR22cP0OlPCZqCV/MVVJC
          GkhW7UKJJpo+7d7qCZT8q+L3Ns3WoC4cIo2vVUmS3tVFahUUhvg1QOcFQotVGDZQQD7Yb
          labK4k6ATLJjwZzwn/0nevD6hqu8uKRQyqmqiX+jL0FH7iYpJe+jm5RmNeYOWzYhHN98E
          EAKuM+xsXRvnQOE3on5EgOSqnfGQIuHmiN+R5qT/ankxvF4scvV1Ykkxt1efxXTzcO+W6
          Kh8Tdafkd7zI6WX/4UceHs93bHxLcpPx+QkypyqERO4J2VyfEl3bgsmW6j3W7WYtaKJdH
          hajQbSx/cdZAztUlGzEAb/SmaiNG0rHzNt21n7GRBNof4Harog25ejjaA8YjZKiEX5pI+
          4cGQY0u6h+YGzBqtNvdRzHp2zOySqm3ZJPkGtWU3ybH6Byl5zc5886cmSGz/Xw=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - oFAx/ByHGrKijTs40TIhY8hiobViVNYv6n4Obc6k0K59TbDDp8DB3bfU1tNsUUHI0KDfl
          +K84qYnzKAN3/1BYz0hRYYuRtADYFE3gCOg0Ddho+JN0gn3ekZJuG9XswXC9mhxRKIVvH
          O7i3H2aDZ+PFRs/2//fgLgcA4UYz+qpFdgFJplCeVo6r/a+gPBjdhF8OVG94wWMIPULbG
          9Iva5Q/INLzUYODFiyYZEMAp+Cz0ZHvRnOYw0of3ymaEKXHec9yooee4EsqqG7R28WPl6
          AnXodZuibZYkEQrQvsp2ImUoAafNhaQMla391fbPu1un2YbJpaFrOOfBF+1AO7mjiZ0SN
          o2B/OT8LJvtHmLAMOyxTSFx2eF7lREAAfX7dFdeEgeyEAzU0HEZcWRGFYK+DGvhrCEE1K
          u3m03s1II0GEL6NTSceiBVMyqiPdWosgDt+ROQDaE2SGjb5P5LcGkHdhduuwFuc2flfJV
          SOK3fxvqC1SPvzzFx9s55+Jk+J/t9/W8FG3MrfJLMqwyYt9vk0QPS9HGOa36W8DYC3F3m
          MzrOfmNuB1muRkWeV/NhKgB0xOTzK5wdADLrBw0kFy+iiU84k36SRiHQWZqFJgW3aYBkL
          nMNQkovv915jh4zjchfIx1838dI21zrnhL+QspihT8qNBSll01XSKd3Bsv7Uc8=

- semaphore:
    name: semaphore-container-image-ceph-ansible-push-quincy
    max: 1

- semaphore:
    name: semaphore-container-image-ceph-ansible-push-reef
    max: 1

- semaphore:
    name: semaphore-container-image-ceph-ansible-push-squid
    max: 1

- job:
    name: container-image-ceph-ansible-build
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: container-image-ceph-ansible-build-quincy
    parent: container-image-ceph-ansible-build
    vars:
      version_ceph: quincy

- job:
    name: container-image-ceph-ansible-build-reef
    parent: container-image-ceph-ansible-build
    vars:
      version_ceph: reef

- job:
    name: container-image-ceph-ansible-build-squid
    parent: container-image-ceph-ansible-build
    vars:
      version_ceph: squid

- job:
    name: container-image-ceph-ansible-push-quincy
    parent: container-image-ceph-ansible-build
    semaphores:
      - name: semaphore-container-image-ceph-ansible-push-quincy
    vars:
      version_ceph: quincy
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_CEPH_ANSIBLE
        pass-to-parent: true

- job:
    name: container-image-ceph-ansible-push-reef
    parent: container-image-ceph-ansible-build
    semaphores:
      - name: semaphore-container-image-ceph-ansible-push-reef
    vars:
      version_ceph: reef
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_CEPH_ANSIBLE
        pass-to-parent: true

- job:
    name: container-image-ceph-ansible-push-squid
    parent: container-image-ceph-ansible-build
    semaphores:
      - name: semaphore-container-image-ceph-ansible-push-squid
    vars:
      version_ceph: squid
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_CEPH_ANSIBLE
        pass-to-parent: true

- job:
    name: container-image-ceph-ansible-release
    parent: container-image-ceph-ansible-build
    vars:
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_CEPH_ANSIBLE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
        - container-image-ceph-ansible-build-quincy
        - container-image-ceph-ansible-build-reef
        - container-image-ceph-ansible-build-squid
    gate:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-midnight:
      jobs:
        - container-image-ceph-ansible-push-quincy
        - container-image-ceph-ansible-push-reef
        - container-image-ceph-ansible-push-squid
    post:
      jobs:
        - container-image-ceph-ansible-push-quincy:
            branches: main
        - container-image-ceph-ansible-push-reef:
            branches: main
        - container-image-ceph-ansible-push-squid:
            branches: main
    tag:
      jobs:
        - container-image-ceph-ansible-release
