---
- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - yamllint
        - flake8
    gate:
      jobs:
        - ansible-lint
        - yamllint
        - flake8
