---
- secret:
    name: SECRET_CONTAINER_IMAGE_CEPH_ANSIBLE
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - l0biyyA7Yl7eF/xXc3yrGr9p7Jg43Rx1+LUbnZ/98Fh/jFRB3fM3DVxCWSOkyd5uGrLDS
          IMnGFrp9WmpIw5RgiVK6gW7D3G/FZE2EJn7WSw94n56dz49LapEouguv8A1NiV4phBW25
          L+D4Bug5SbfGBvI/NRLBcArodawxyYu3/FRG7lsgPCgsPGXcY/l7u88pd0XJEo/IMUsHb
          XwuhOAzI9/H6zYfFh1n+Wlvn9+mlxgJBNQVKeP//WEhbxPtp4a3P35iQ5wHnjjLFH+4BL
          ddA7GqqxZVkrlsdhGGtIyc/DDYWuTBNQgADMMGnXlO3ObJRAl7IOGUS2eOadnzV8EafAM
          SmSzhHbJocYipvJM5WJJXA5oWgxG+CB8gnn4m+7AkPUOc43oZTmTXEQNNtg4PALfZNMvn
          u5JbJ3WlTObwRNq+dMn5q4eYTtsODDOtWzztM4zZkvq07tjZ5lZylitZc/eePysF26sYQ
          A8GHbgpfRKq1t97mjWeT4h5FGGlW5Ql/STjZb4DQpgc55U0d7YyNHkIBOexfeINSNULZ/
          8THAGjfW3wyMaaYZlKU16xcyc60x6WkXGPda9DIAyN3f5ouYt9y6iDjfLO6G5fdrG3gMF
          TWrNXo6WSfHK0MHIqxw68t5BveD5JRXFcPPkT2FbS1bSwHSwpJ6bVAb7y8PbVg=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - JYDswL5G9I//wPXt1/oyJpQR5sqLDwWUOzv61SxS5a6dnojtY8H1Iizm4UmtirgdhenF/
          RUGEuHQbHK8GzDrfOSF73mrPC+gt0C2S9MwfKXg3kvo4UBu149uSuLj3mYrkOsGzwxHcC
          G3agzfqxDqYbwMILnRdwWGPNE2Igbjr3RtoIaK3WigeC05jzQhv3aB3f44tl4VTgk7QOq
          2xQQjZKSpCeAL9X5oIr1O6NG/jyr4sWm3/R1d4xUDt8psWAsw/2Ws/wxQErzlw2TeQai4
          yU0bK6RRVo3P32bn6vrRjUgjHch18PR+D5G3/Lp8KNXJzxskHz/agpwwXZ/poRY5ubqa0
          CK56Mq/3N7dBu1kVVNKIdzHx8ZYhcnsGYBEONyJA3ttnE8FSZWC91sA6vnDybOG0JoI0K
          Sn2v3xkT0+4X83Gi0KWubMlmX32tunpxYthFusRicBMHYiNkqoz6eQSjguyxcVyBw/Smm
          0qMs0Mam4k9NqkUFiNwOD/DEfPqMBZooa3hDJAeyIV3RM52s1M2Nu+n3tclI6dCMy6KZq
          BE7LqKMKsOz2YVPKXxl3KZ9/ZH57pzvHx5T64JzJ/84nN6DEJjoZXkTKD1TiHtzQdgdgi
          Rb0IdDRosknMSUDaCJ5dAqmlienx6BnRVwjXarKomj29YhAzxuSviU4n5v3RMg=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - XTAv0tc2ZOnAh0VSn3QyIS1kgq0ki+/+UxKKRhqK6YTdrfKVM6AmscwSb8gbZuChkwUDE
          +vOWF9kyj0tewIxqc2l5BSydDltRULx0yAS9V5urwbqlJdrcgldQZDwgqOnMtC+SbO36T
          JfUyxsFE5PMwqp8oDIX3q/1QVKUCSwsTBokro/NzCwOwDVMtcbsOgPjDuOL40ONaE5gSK
          syjD44LGfMGZNwf+l3AQAZsi6szlpL7oBKLIO9y+xyjx6qiEb+bmlwIoo3vIQx3z3fRJo
          pNrYcqZgXCIF18+QXqGUr6GFCN/eEGDbuQBQVtAOYwQCnW/xaRkgq/u7eCHR/wFxc/Gdm
          xdGZtYSrnBJl14vyxJDb2d21zaMJlu1a4Da6BwM5mW21+HV35WxwIjVHbQ3+uDnNp5LBI
          GSvYFv2L2weaNxpeMiSI7oDW5gxcdKNcMrmlAUZLPrvALFyu1MlsZCwklY4wTLrfPJhET
          SyMhb2Yi+aXNJPoXU9l1j5al2paMYwQYm+LeAxYgNsTGCrZ0u4MhsgZlBfClwW8dghqGr
          /JEiu/9PCmdjFUhALmjVDl25hI+7ifBrjtFfq+MvAmB84KIylub9STb4Jq7+B6+O6ENNl
          /uzowymPS1ymbDCIG2bn3BLlCASrsNGA31LBMtEi+kWc+lHfoAu7Du4EzcL1tg=

- semaphore:
    name: semaphore-container-image-ceph-ansible-push-quincy
    max: 1

- semaphore:
    name: semaphore-container-image-ceph-ansible-push-reef
    max: 1

- job:
    name: container-image-ceph-ansible-build
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: container-image-ceph-ansible-build-quincy
    parent: container-image-ceph-ansible-build
    vars:
      version_ceph: quincy

- job:
    name: container-image-ceph-ansible-build-reef
    parent: container-image-ceph-ansible-build
    vars:
      version_ceph: reef

- job:
    name: container-image-ceph-ansible-push-quincy
    parent: container-image-ceph-ansible-build
    semaphores:
      - name: semaphore-container-image-ceph-ansible-push-quincy
    vars:
      version_ceph: quincy
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_CEPH_ANSIBLE
        pass-to-parent: true

- job:
    name: container-image-ceph-ansible-push-reef
    parent: container-image-ceph-ansible-build
    semaphores:
      - name: semaphore-container-image-ceph-ansible-push-reef
    vars:
      version_ceph: reef
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_CEPH_ANSIBLE
        pass-to-parent: true

- job:
    name: container-image-ceph-ansible-release
    parent: container-image-ceph-ansible-build
    vars:
      push_image: true
      push_sbom: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_CEPH_ANSIBLE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
        - container-image-ceph-ansible-build-quincy
        - container-image-ceph-ansible-build-reef
    gate:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-midnight:
      jobs:
        - container-image-ceph-ansible-push-quincy
        - container-image-ceph-ansible-push-reef
    post:
      jobs:
        - container-image-ceph-ansible-push-quincy:
            branches: main
        - container-image-ceph-ansible-push-reef:
            branches: main
    tag:
      jobs:
        - container-image-ceph-ansible-release
