---
- name: Apply role ceph-mon
  gather_facts: false
  hosts: ceph-mon
  become: true

  vars_files:
    - /opt/configuration/environments/configuration.yml
    - /opt/configuration/environments/images.yml
    - /opt/configuration/environments/secrets.yml
    - /opt/configuration/environments/ceph/configuration.yml
    - /opt/configuration/environments/ceph/images.yml
    - /opt/configuration/environments/ceph/secrets.yml

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-mon
  serial: 1 # MUST be '1' WHEN DEPLOYING MONITORS ON DOCKER CONTAINERS
