---
- name: Apply role ceph-mon
  gather_facts: false
  hosts: ceph-mon
  become: true

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-mon
  serial: 1  # MUST be '1' WHEN DEPLOYING MONITORS ON DOCKER CONTAINERS
