---
- name: Prepare docker and configuration
  gather_facts: false
  hosts: ceph
  become: true

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config

- name: Deploy monitor services
  gather_facts: false
  hosts: ceph
  become: true
  serial: 1

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-mon

- name: Deploy mgr, osd, and mds services
  gather_facts: false
  hosts: ceph
  become: true

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-mgr
    - ceph-osd
    - ceph-mds
