---
- name: Apply role ceph-config
  gather_facts: false
  hosts: "{{ ceph_group_name|default('ceph') }}"
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-config
