---
- name: Apply role ceph-iscsigw
  gather_facts: false
  hosts: "{{ iscsi_gw_group_name|default('ceph-iscsigw') }}"
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-iscsi-gw
