---
- name: Apply role ceph-rgw
  gather_facts: false
  hosts: "{{ rgw_group_name|default('ceph-rgw') }}"
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-rgw
