---
- name: Deploy ceph environment
  hosts: "{{ ceph_group_name|default('ceph') }}"
  become: true

  roles:
    - role: ceph-defaults
    - role: ceph-facts
    - role: ceph-infra
    - role: ceph-handler
    - role: ceph-container-common
    - role: ceph-config
    - role: ceph-mon
    - role: ceph-mgr
    - role: ceph-osd
    - role: ceph-crash
      when: enable_ceph_crash|default(true)|bool
    - role: ceph-mds
      when: enable_ceph_mds|default(false)|bool
    - role: ceph-rgw
      when: enable_ceph_rgw|default(false)|bool
