---
- name: Apply role ceph-nfs
  gather_facts: false
  hosts: "{{ nfs_group_name|default('ceph-nfs') }}"
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-nfs
