---
- name: Apply role ceph-mgr
  gather_facts: false
  hosts: ceph-mgr
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-mgr
