---
- name: Apply role ceph-rbd-mirror
  hosts: ceph-rbd-mirror
  gather_facts: false
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-rbd-mirror
