---
- name: Apply role fetch-keys
  gather_facts: false
  hosts: "{{ mon_group_name|default('ceph-mon') }}[0]"
  become: true
  strategy: "{{ osism_strategy|default('linear') }}"

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-fetch-keys
