---
- name: Apply role ceph-rgw
  hosts: "{{ rgw_group_name|default('ceph-rgw') }}"
  become: true
  serial: '{{ ceph_serial|default("0") }}'
  strategy: "{{ osism_strategy|default('linear') }}"

  vars:
    ceph_handler_crash_restart: false
    ceph_handler_mdss_restart: false
    ceph_handler_mgrs_restart: false
    ceph_handler_mons_restart: false
    ceph_handler_osds_restart: false
    ceph_handler_rbdmirrors_restart: false

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-rgw
