---
- name: Run preparations
  hosts: "{{ ceph_group_name|default('ceph') }}"
  become: true
  strategy: "{{ osism_strategy|default('linear') }}"

  roles:
    - ceph-defaults
    - ceph-facts

- name: Apply role ceph-crash
  hosts: "{{ ceph_group_name|default('ceph') }}"
  become: true
  serial: '{{ ceph_serial|default("0") }}'
  strategy: "{{ osism_strategy|default('linear') }}"

  vars:
    ceph_handler_mdss_restart: false
    ceph_handler_mgrs_restart: false
    ceph_handler_mons_restart: false
    ceph_handler_osds_restart: false
    ceph_handler_rbdmirrors_restart: false
    ceph_handler_rgws_restart: false

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-crash
