---
- name: Apply role ceph-mgr
  hosts: "{{ mgr_group_name|default('ceph-mgr') }}"
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-mgr
