---
- name: Run preparations
  gather_facts: false
  hosts: ceph
  become: true
  roles:
    - ceph-defaults
    - ceph-facts

- name: Apply role ceph-crash
  gather_facts: false
  hosts: ceph
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-crash
