---
- name: Run preparations
  hosts: "{{ ceph_group_name|default('ceph') }}"
  become: true
  roles:
    - ceph-defaults
    - ceph-facts

- name: Apply role ceph-osd
  hosts: "{{ osd_group_name|default('ceph-osd') }}"
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-osd
