---
- name: Apply role ceph-client
  hosts: "{{ client_group_name|default('ceph-client') }}"
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-container-common
    - ceph-config
    - ceph-client
