---
- name: Gather facts for ceph hosts
  hosts: ceph
  gather_facts: false
  tasks:
    - setup:

- name: Gather facts for ceph hosts (if using --limit)
  hosts: ceph
  gather_facts: false
  tasks:
    - setup:
      delegate_facts: true
      delegate_to: "{{ item }}"
      with_items: "{{ groups['ceph'] }}"
      when:
        - (play_hosts | length) != (groups['ceph'] | length)

- name: Apply role ceph-facts
  hosts: ceph
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
