#!/usr/bin/env bash
set -x

# DO NOT EDIT THIS FILE BY HAND -- FILE IS SYNCHRONIZED REGULARLY

# Available environment variables
#
# REPOSITORY
# VERSION

docker push "$REPOSITORY:$VERSION"
docker rmi "$REPOSITORY:$VERSION"
