---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  build-container-image:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ceph_version:
          - pacific
          - quincy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build container image
        run: scripts/build.sh
        env:
          CEPH_VERSION: ${{ matrix.ceph_version }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/ceph-ansible

      - name: Get short revision ID
        id: revision
        shell: bash
        run: echo "::set-output name=short::$(git rev-parse --short HEAD)"

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          artifact-name: ceph-ansible-${{ matrix.ceph_version }}.spdx
          image: "ceph-ansible:${{ steps.revision.outputs.short }}"

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          CEPH_VERSION: ${{ matrix.ceph_version }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: osism/ceph-ansible
        if: |
          github.repository == 'osism/container-image-ceph-ansible' &&
          github.ref == 'refs/heads/main'
