---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8-22 * * *"
  push:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - patches/**
      - scripts/**
  pull_request:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - patches/**
      - scripts/**

jobs:
  build-container-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ceph_version:
          - nautilus
          - octopus
          - pacific

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - run: scripts/build.sh
        env:
          CEPH_VERSION: ${{ matrix.ceph_version }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/ceph-ansible
      - run: |
          scripts/push.sh
        env:
          CEPH_VERSION: ${{ matrix.ceph_version }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: osism/ceph-ansible
        if: |
          github.repository == 'osism/container-image-ceph-ansible' &&
          github.ref == 'refs/heads/main'
