---
name: Build docker image

"on":
  schedule:
    - cron: "0 8-22 * * *"
  push:
    paths:
      - .github/workflows/build-docker-image.yml
      - Containerfile
      - files/**
      - patches/**
  pull_request:
    paths:
      - .github/workflows/build-docker-image.yml
      - Containerfile
      - files/**
      - patches/**

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ceph_version:
          - octopus
          - pacific

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'
      - run: scripts/build.sh
        env:
          CEPH_VERSION: ${{ matrix.ceph_version }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/ceph-ansible
      - run: |
          scripts/push.sh
        env:
          CEPH_VERSION: ${{ matrix.ceph_version }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/ceph-ansible
        if: github.ref == 'refs/heads/master'
