---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8-22 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  build-container-image:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ceph_version:
          - octopus
          - pacific
          - quincy

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - run: scripts/build.sh
        env:
          CEPH_VERSION: ${{ matrix.ceph_version }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/ceph-ansible
      - run: |
          scripts/push.sh
        env:
          CEPH_VERSION: ${{ matrix.ceph_version }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: osism/ceph-ansible
        if: |
          github.repository == 'osism/container-image-ceph-ansible' &&
          github.ref == 'refs/heads/main'
